version: "3.8"
services:
  backend:
    build: ./backend
    container_name: fhir-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: fhir-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm run dev
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
